version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '3:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 99
    reviewers:
      - 9renpoto
    labels:
      - 'Type: dependencies'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '3:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - 9renpoto
    labels:
      - 'Type: dependencies'
