version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Do not merge when it is marked work in progress (WIP)
        must_exclude:
          regex: ^\[WIP\]
          message: This is work in progress. Do not merge yet.
        # Enforce semantic release convention.
      - do: label
        must_include:
          regex: ^Type
          message: must include types
  - when: pull_request.*, pull_request_review.*, issues.*
    validae:
      - do: project
        must_include:
          regex: ^Thinking
          message: must include project
      - do: assignee
        max:
          count: 1 # There should not be more than 2 assignees
          message: 'test string' # this is optional
        min:
          count: 1 # min number of assignees
          message: 'test string' # this is optional
