language: node_js
sudo: false
node_js:
- stable
- 6
- 5
cache:
  directories:
  - node_modules
after_success:
- npm run codecov
- '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && npm
  run deploy-storybook'
notifications:
  email: false
  slack:
    secure: qDisnttj7h7QGW85NRYOOX+Mj+y5QSd4k6JtmdqPNkneE7CNH4phJLyOaOwjvMMknEwvBdhSww6e1Z/tnUDA69J1wxzMmO7U1mHpUq6jj38dVb3C4rPh3toyGD2hjtJl/F069R1e3jeqESzz/dBTh+oWq/ZTgS758qfP3YdkF11CG/5N6ERoWSv+Dk5MY6EU3HglklqApUTKLDEz6cqae7nfcngR610JkykjIr6neDgmFnGKvtX0BaWmjl69DmB0/98yzNWWgdSrjTQKp/auiNOy8BVdVe6HlPIoJaJxKzUTi7WYTTIBiRfpMOOR5ZCs6Ek4p4BnR7Rs/er/sVrhrfWjMvRl0LY3LOTnEhtocBWWNZ+5J6blNbqEViokyoFLGAFR4B5y+PZUMC4NqayRy4BwmAp3P1kgVl/gWoRz5mQ84xZCS9779SvCK4xf0ZbKau6yUcVBJNvyV7IW0403A/DR8i4Le44e+YAV25W5/w+HrJ5jGhCruV10/kNtjbVq2mcn6BTIGyayLSTnAG51NkNmioCuAUiLHzCd2rbmOHoamEPiZX/dMWmnuj2qQno2HyOPAIKnJOttm21tEpXzS+IHwvbo2TMrQnNIvZAm9aSpv+Ku08AWGxVY6ZdYlGyuKwmUIo7jWAoGMIyCRaYeEJSDsGUsPX9Ghorb13dUIfs=
env:
  global:
    - GIT_COMMITTER_NAME='Keisuke Kan@travis-ci'
    - GIT_COMMITTER_EMAIL='9renpoto@gmail.com'
    - GIT_AUTHOR_NAME='Keisuke Kan@travis-ci'
    - GIT_AUTHOR_EMAIL='9renpoto@gmail.com'
    - secure: sG8guqPD/X4y1knm6ibyB+mqbVLJnlsCKE0JsMZModaRpt5D9fRdcqoB44uw6bL+oBBG9hLV/KO+SRPuG4+iZ3gHPaunROmV+x7ejcrRQi/QO5vsadwWDGMYZ+bpQYhQQN6mayUmlU/Dq0y71WDGrvxQBXyAZWId0g2M5V10NkzGzoFBiVSC8Szdfm464smqBjoFbL6SdfZw6KHQVMZQwFmsO9CkIm+jBIWNFUoGOloS4OATawJvRBtQeqdnQz1gEhS4dydKDatyJOS1csUpz0dpX+5GmS+ZcLGEWEcRGq1clDoMrTQNcAeLUKMpgJkIGIazPpN6fee6nJaCD7lEZkGbsIFEXtrUmwHZUS58SDHJ/sYw0JqTytcWdNi2P6Y8pBBfXQOGvJ/Q274Eycv+KnMqnoFrqjNqdGblF7vilxB4Jrn/RW5GywnXFtP4STaecvOxnFFTQlJc7vjpSBTvd2CzJVuCKWr0F2yJPRlrbmE1vFPqoZr3yOogdnvw8ue4U/qVWLQntAEOsaNeejpi11r3KHxPooFOuI81O6ohQjuT93xDjsVtcJQcBx03pzo0xBoy3UBd+LsVwE9zAtVX/0hJVBabiPMJuDnodEtL2CexfjL2432VeT3JmEZblaYVqHaWQjS9j0fn/7576xN3TAXlfqMzu9WDB0F1frSEC2w=
