language: node_js
node_js:
- stable
- "lts/*"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
env:
  matrix:
  - CMD=lint
  - CMD=test
before_install:
- export TZ=Asia/Tokyo
script:
- yarn workspace @9renpoto/nest start &
- yarn build
- yarn $CMD
after_success:
- '[ "$CMD" == "test" ] && yarn coverage'
notifications:
  email: false
