language: node_js
node_js:
- stable
- "lts/*"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
env:
  matrix:
  - CMD=lint
  - CMD=test
script:
- yarn build
- '[ "$CMD" == "lint" ] && npx eslint . --ext=ts,tsx'
- yarn $CMD
after_success:
- '[ "$CMD" == "test" ] && yarn coverage'
notifications:
  email: false
