language: node_js
node_js:
- stable
- "lts/*"
env:
  matrix:
  - CMD=build
  - CMD=lint
  - CMD=test
script:
- yarn $CMD
after_success:
- '[ "$CMD" == "test" ] && yarn coverage'
notifications:
  email: false
