language: node_js
node_js:
- stable
- "lts/*"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
env:
  matrix:
  - CMD=build
  - CMD=lint
  - CMD=test
script:
- cat .envrc.tmpl >> $BASH_ENV
- source $BASH_ENV
- yarn $CMD
after_success:
- '[ "$CMD" == "test" ] && yarn coverage'
notifications:
  email: false
