language: node_js
services:
- postgresql
node_js:
- stable
- "lts/*"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
env:
  matrix:
  - CMD=test
  - CMD=migrate:generate
before_install:
- export TZ=Asia/Tokyo
- psql -c 'create database thinking_face;' -U postgres
script:
- yarn workspace @9renpoto/nest start &
- sleep 15
- yarn build
- yarn $CMD
after_success:
- '[ "$CMD" == "test" ] && yarn coverage'
notifications:
  email: false
