codecov:
  token: 8b421743-a96e-41ee-8046-45a9fdff3e1b

coverage:
  precision: 2
  round: down
  range: "90...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
