name: Deploy

on:
  push:
    branches:
      - feature/deploy
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install --production --frozen-lockfile
      - name: Build
        run: yarn workspace @9renpoto/blog build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: blog
          path: apps/blog/public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: blog
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: apps/blog
