name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn workspace @9renpoto/blog build
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v1
        with:
          name: blog
          path: apps/blog/public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: blog
          path: apps/blog/public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: apps/blog
