name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn lint
          yarn test
        env:
          CI: true
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

  sandbox-sapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          build: |
            yarn install --frozen-lockfile
            yarn build --scope @9renpoto/sapper
          dist: sandbox/sapper/__sapper__/export
